### ISSUE TITLE
Where is this language stored on the local machine?

### ISSUE THREAD

**Issue by dsifford** [atom/language-gfm#129]
Sorry about this issue, but I've Googled and looked and I just can not locate where this is stored on my local machine. I'm trying to extend the grammar to highlight Mathjax equations surrounded in `$` or `$$`

I'm running Windows 10, Atom 1.1.0-beta1

Didn't there used to be a `View Code` button to quickly navigate to this folder? Where did that go?

Thanks for the help.

**Comment by 50Wliu** [comment]
@dsifford I think the code is hidden away in an `.asar` archive so that Atom loads faster (but as a result, you can no longer access it).  If you want to extend this grammar, I instead suggest you `git clone` and then `apm link` it.  This is better than changing the bundled code for a variety of reasons: 1) your changes aren't overwritten whenever Atom updates, 2) you can make a PR to include your changes, and 3) you can run specs to make sure everything's still working.

I hope that helps!

**Comment by dsifford** [comment]
Thanks for the clarification!
