### ISSUE TITLE
Way to switch off the autocomplete suggestions?

### ISSUE THREAD

**Issue by werunom** [atom/language-gfm#226]
In markdown files, I get autocomplete suggestions like the following - 
typing `b` shows suggestion for `bold text`
typing `i` shows suggestion for `italic text`
`img` for `embedded image`
`ref` for `reference`, etc.

Is there a way to stop these suggestions? I know I can completely turn off the suggestions for *.md files. But I want suggestions from other packages (like `autocomplete-bibtex`). So, is there a way to switch off the ones given by this language alone?

PS - I have few markdown packages. Among these, I disabled `md-writer`and still got the suggestions. Hence i am assuming that these suggestions are coming from this language package.

**Comment by rsese** [comment]
As far as I know, you can't disable snippets included from a package, see https://github.com/atom/snippets/issues/55.

I guess one option is to use an alternative package like [language-markdown](https://atom.io/packages/language-markdown)?  The package is a replacement for language-gfm (and it disables language-gfm on install) and it doesn't have snippets included I think.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
