### ISSUE TITLE
LaTeX inline highlighting (pandoc flavored)

### ISSUE THREAD

**Issue by nylki** [atom/language-gfm#81]
I know this is supposed to be github flavored markdown.  However a number of people are using *language-gfm* to write their markdown files to be compiled and rendered to pdf via *pandoc*.

Is it in the scope of this language package to add highlighting of inline LaTeX code in eg. the [math-dollars](http://johnmacfarlane.net/pandoc/README.html#math)? I am asking because I get the [occasional request](https://github.com/nylki/pen-paper-coffee-syntax/issues?q=label%3A%22language-package+related%22+is%3Aclosed) wether my syntax theme could highlight pandoc features, which I unfortunately have to dismiss because it's not the task of a syntax theme.

If it is not in the scope of this package, I will try to implement some of those features in a separate package if I get the time… Or wait until somebody does so.

thanks for listening! :)

**Comment by ryanp-me** [comment]
I agree highlighting of certain pandoc features would be nice, but I'm wondering where the line needs to be drawn. Pandoc can vary quite a bit and I'm wondering if we would be better off making a language package specifically for it. (That being said, I don't know how language packages work and don't have the time to do this right now.)

At the very least, it would be nice if we could ignore the contents of math blocks, since it prevents the rest of the document from being highlighted:

![screen shot 2015-03-08 at 6 15 57 pm](https://cloud.githubusercontent.com/assets/877638/6548670/3c18025a-c5c6-11e4-898d-134a7991f0ad.png)

**Comment by nylki** [comment]
closing in favor of https://github.com/leipert/language-pfm
