### ISSUE TITLE
Highlighting YAML blocks in Pandoc Markdown files

### ISSUE THREAD

**Issue by izuzak** [atom/language-gfm#83]
_From @juh2 on March 31, 2015 7:13_

Hi,

pandoc parses a YAML block in markdown files to set metadata and template variables. Highlighting in Github Markdown does not work correctly, when I use a YAML block with a multiline entry. The attached screenshots show the behaviour.

In One Light all the rest of the text gets green. I am using Atom 0.188.0

![correct-highlighting](https://cloud.githubusercontent.com/assets/1416069/6913899/cf4413c2-d785-11e4-8695-e2dbdab03d5d.png)
![wrong-hightlighting](https://cloud.githubusercontent.com/assets/1416069/6913934/0a699a80-d786-11e4-8b54-4d6bb7201960.png)

_Copied from original issue: atom/atom#6182_

**Comment by thomasjo** [comment]
Unless this has changed recently YAML front-matter is supposed to be escaped by leading and trailing `---`, but you're attempting to end the front-matter with `...`. Fixing this should resolve your problem.

**Comment by izuzak** [comment]
I think you're right, @thomasjo -- great catch :zap:, totally missed that. Gonna close this for now.

**Comment by juh2** [comment]
Ending with ... is common at least in the pandoc world.

**Comment by izuzak** [comment]
@juh2 Thanks for clarifying! For future reference -- we'd appreciate it if you included links to the relevant documentation so that it's easier to verify things like these.

As far as I can tell, `...` is not accepted on GitHub as a way to terminate a YAML block, so adding that here might be confusing since this is a package for _GitHub_ Flavored Markdown and it would increase the difference between the two. One thing you might consider is to create a new package (perhaps a fork of this one), add support for `...` in that package and use it instead of this one. That's the nice thing about Atom -- you can add and replace anything.

**Comment by juh2** [comment]
Ok.

See http://www.yaml.org/spec/1.2/spec.html  chapter 2.2. Structures
or
http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#yaml-metadata-block

I had the fear that forking the package would be the option, as I assumed that you have to terminate a YAML-block in GFM with three dashes only.

In Pandoc and other systems dashes and dots work. I don't know if there are any side effects when using dashes instead of dots, but I can use dashes in the future as this seems to be easier than to fork the package. ;-)

The common mark specs seems to be YAML agnostic. http://spec.commonmark.org/0.18/
